### PR TITLE
Systemd doc fixes

### PR DESCRIPTION
**Pull request by ldidry**

### CODE REVIEW

**Comment by ldidry** [comment]
I removed `ihatemoney.service` from `conf` because it’s a folder used by docker, not for putting doc in it.

**Comment by ldidry** [comment]
I moved `pip install gunicorn` because it’s useless if you deploy with Apache.

**Comment by almet** [comment]
Okay, perfect, thanks!

**Comment by almet** [comment]
Est-ce que tu peux faire une PR sur le dépot upstream?

**Comment by ldidry** [comment]
Ça marche

**Pull request merged**
